name: Sequential jobs
on: push
jobs:
  first: # 依存ジョブがないので最初に実行される
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "First job"
  second: # firstジョブの後に実行される
    runs-on: ubuntu-latest
    needs: [first] # needsキーへ依存するfirstジョブを指定
    steps:
      - run: sleep 5 && echo "Second job"
  third: # secondジョブの後に実行される
    runs-on: ubuntu-latest
    needs: [second] # needsキーへ依存するsecondジョブを指定
    steps:
      - run: sleep 2 && echo "Third job"
